language: cpp
compiler: gcc

env: CMAKE_CMD_OPTION="-DENABLE_TESTING=1"

matrix:
  include:
    - os: linux
      sudo: false
      compiler: gcc
      env: CMAKE_CMD_OPTION="-DENABLE_COVERAGE=1"

    - os: osx
      compiler: xcode6.4

    - os: osx
      compiler: xcode8
addons:
  apt:
    packages:
      - cmake
      - libboost-all-dev
      - libboost-test-dev
      - lcov

script:
  - mkdir build
  - cd build
  - cmake .. $CMAKE_CMD_OPTION
  - make -j 2
  - make test

# Hook code coverage report with codecov.io
after_success:
  # Creating report
  - make gcov
  - make lcov
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
